import './bit-c3.less';
import './chart';
import './data/data';
import './data/column/column';
import './data/group/group';
import './data/name/name';
import './data/type/type';
import './y-grid/y-grid';
import './y-grid/y-grid-line/y-grid-line';